# Generated by Django 6.0.5 on 2026-05-09 22:05

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listeningquestion_audio_file_securityalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedAudioStorage(), upload_to='listening_audio/', verbose_name='File audio b\\u1ea3o m\\u1eadt'),
        ),
    ]
