# Generated by Django 6.0.5 on 2026-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_part2topic_part2voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='part2topic',
            name='data_choices',
            field=models.TextField(blank=True, help_text='Nhập nhiều dòng dữ liệu đáp án. 4 voice sẽ chọn đáp án đúng từ danh sách này.', verbose_name='Dữ liệu đáp án tổng'),
        ),
    ]
