# Generated by Django 6.0.5 on 2026-05-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_part2topic_data_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='part2topic',
            name='audio_url',
            field=models.URLField(blank=True, verbose_name='Audio Drive chung'),
        ),
        migrations.AddField(
            model_name='part2voice',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Khóa'),
        ),
        migrations.AddField(
            model_name='part2voice',
            name='question_text',
            field=models.TextField(blank=True, verbose_name='Câu hỏi'),
        ),
    ]
