# Generated by Django 6.0.5 on 2026-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_part2topic_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='part2voice',
            name='correct_data',
            field=models.TextField(blank=True, verbose_name='Đáp án đúng'),
        ),
    ]
