# Generated by Django 6.0.5 on 2026-05-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_listeningpartmaterial_listeningpartquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Tên thumbnail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='login_thumbnails/', verbose_name='Ảnh thumbnail upload')),
                ('image_url', models.URLField(blank=True, verbose_name='Đường dẫn ảnh thumbnail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thumbnail đăng nhập',
                'verbose_name_plural': 'Thumbnail đăng nhập',
            },
        ),
        migrations.CreateModel(
            name='SiteBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Tên ảnh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Ảnh nền upload')),
                ('image_url', models.URLField(blank=True, verbose_name='Đường dẫn ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ảnh nền giao diện',
                'verbose_name_plural': 'Ảnh nền giao diện',
            },
        ),
    ]
