# Generated by Django 6.0.5 on 2026-05-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_loginthumbnail_sitebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebackground',
            name='ticker_text_1',
            field=models.CharField(blank=True, default='18 HỌC VIÊN ĐÃ ĐĂNG KÝ', max_length=255, verbose_name='Chữ chạy 1'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='ticker_text_2',
            field=models.CharField(blank=True, default='CAM KẾT B1+ APTIS', max_length=255, verbose_name='Chữ chạy 2'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='ticker_text_3',
            field=models.CharField(blank=True, default='30 NGÀY TĂNG TỐC', max_length=255, verbose_name='Chữ chạy 3'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='ticker_text_4',
            field=models.CharField(blank=True, default='KÈM 1:1 LINH HOẠT', max_length=255, verbose_name='Chữ chạy 4'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='ticker_text_5',
            field=models.CharField(blank=True, default='LUYỆN NGHE 4 PART', max_length=255, verbose_name='Chữ chạy 5'),
        ),
    ]
