# Generated by Django 6.0.5 on 2026-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_homebackground_ticker_text_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseThumbnailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Thumbnail khóa học online', max_length=255, verbose_name='Tên thumbnail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='Ảnh thumbnail')),
                ('image_url', models.URLField(blank=True, verbose_name='Link ảnh thumbnail')),
                ('video', models.FileField(blank=True, null=True, upload_to='course_thumbnail_videos/', verbose_name='Video thumbnail')),
                ('video_url', models.URLField(blank=True, verbose_name='Link video thumbnail')),
                ('title', models.CharField(blank=True, default='KHÓA HỌC ONLINE', max_length=255, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, default='Video bài giảng • Lộ trình • Bài tập • Tài liệu • Chứng chỉ', max_length=255, verbose_name='Mô tả ngắn')),
                ('card_opacity', models.PositiveIntegerField(default=92, verbose_name='Độ đậm khung')),
                ('background_blur', models.PositiveIntegerField(default=4, verbose_name='Độ mờ nền')),
                ('card_scale', models.PositiveIntegerField(default=100, verbose_name='Kích thước khung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thumbnail khóa học',
                'verbose_name_plural': 'Thumbnail khóa học',
            },
        ),
    ]
