# Generated by Django 6.0.5 on 2026-05-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coursethumbnailsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseThumbnailSetting',
        ),
    ]
