# Generated by Django 5.2.14 on 2026-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_coursethumbnailsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginthumbnail',
            options={'verbose_name': 'Thumbnail ??ng nh?p', 'verbose_name_plural': 'Thumbnail ??ng nh?p'},
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='ticker_text_1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ch? ch?y 1'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='ticker_text_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ch? ch?y 2'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='ticker_text_3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ch? ch?y 3'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='ticker_text_4',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ch? ch?y 4'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='ticker_text_5',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ch? ch?y 5'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='login_thumbnail_videos/', verbose_name='Video thumbnail upload'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='???ng d?n video thumbnail'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='login_thumbnails/', verbose_name='?nh thumbnail upload'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='???ng d?n ?nh thumbnail'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='?ang s? d?ng'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='T?n thumbnail'),
        ),
    ]
