# Generated by Django 5.2.14 on 2026-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_loginthumbnail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='login_overlay_images/', verbose_name='?nh n?i 1'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_left_w',
            field=models.PositiveIntegerField(default=26, verbose_name='K?ch th??c ?nh n?i 1 (%)'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_left_x',
            field=models.PositiveIntegerField(default=6, verbose_name='X ?nh n?i 1 (%)'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_left_y',
            field=models.PositiveIntegerField(default=58, verbose_name='Y ?nh n?i 1 (%)'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_right_image',
            field=models.ImageField(blank=True, null=True, upload_to='login_overlay_images/', verbose_name='?nh n?i 2'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_right_w',
            field=models.PositiveIntegerField(default=24, verbose_name='K?ch th??c ?nh n?i 2 (%)'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_right_x',
            field=models.PositiveIntegerField(default=58, verbose_name='X ?nh n?i 2 (%)'),
        ),
        migrations.AddField(
            model_name='loginthumbnail',
            name='overlay_right_y',
            field=models.PositiveIntegerField(default=50, verbose_name='Y ?nh n?i 2 (%)'),
        ),
    ]
