# Generated by Django 5.2.14 on 2026-05-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_loginthumbnail_overlay_left_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOverlayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='login_overlay_images/', verbose_name='?nh n?i')),
                ('x', models.PositiveIntegerField(default=10, verbose_name='X (%)')),
                ('y', models.PositiveIntegerField(default=55, verbose_name='Y (%)')),
                ('w', models.PositiveIntegerField(default=24, verbose_name='K?ch th??c (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Th? t?')),
                ('is_active', models.BooleanField(default=True, verbose_name='?ang d?ng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_images', to='core.loginthumbnail', verbose_name='Thumbnail ??ng nh?p')),
            ],
            options={
                'verbose_name': '?nh n?i ??ng nh?p',
                'verbose_name_plural': '?nh n?i ??ng nh?p',
                'ordering': ['order', 'id'],
            },
        ),
    ]
