# Generated by Django 5.2.14 on 2026-05-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_loginoverlayimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part3Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Part 3 Topic', max_length=255)),
                ('audio_url', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('answer_pool', models.TextField(default='Man\nWoman\nBoth', help_text='One answer option per line.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listeningpartquestion',
            options={'ordering': ['material_id', 'order', 'id'], 'verbose_name': 'Question Listening Part 3/4', 'verbose_name_plural': 'Question Listening Part 3/4'},
        ),
        migrations.AlterModelOptions(
            name='loginoverlayimage',
            options={'ordering': ['order', 'id'], 'verbose_name': '?nh n?i ng nh?p', 'verbose_name_plural': '?nh n?i ng nh?p'},
        ),
        migrations.AlterModelOptions(
            name='loginthumbnail',
            options={'verbose_name': 'Thumbnail ng nh?p', 'verbose_name_plural': 'Thumbnail ng nh?p'},
        ),
        migrations.AlterModelOptions(
            name='part2topic',
            options={'ordering': ['-id'], 'verbose_name': 'Topic Part 2', 'verbose_name_plural': 'Topic Part 2'},
        ),
        migrations.AlterModelOptions(
            name='sitebackground',
            options={'verbose_name': 'Ảnh nền interface', 'verbose_name_plural': 'Ảnh nền interface'},
        ),
        migrations.AlterField(
            model_name='listeningpartmaterial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị cho student'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1, verbose_name='Answer đúng'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500, verbose_name='Answer A'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500, verbose_name='Answer B'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, verbose_name='Answer C'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, verbose_name='Answer D'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='option_e',
            field=models.CharField(blank=True, max_length=500, verbose_name='Answer E'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='option_f',
            field=models.CharField(blank=True, max_length=500, verbose_name='Answer F'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='listeningpartquestion',
            name='question_text',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='voice_info',
            field=models.TextField(blank=True, verbose_name='Information của voice'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='voice_info_locked',
            field=models.BooleanField(default=False, verbose_name='Lock information voice'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tht?'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_images', to='core.loginthumbnail', verbose_name='Thumbnail ng nh?p'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='w',
            field=models.PositiveIntegerField(default=24, verbose_name='K?ch thc (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='?ng d?n ?nh thumbnail'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='?ang sd?ng'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_left_w',
            field=models.PositiveIntegerField(default=26, verbose_name='K?ch thc ?nh n?i 1 (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_right_w',
            field=models.PositiveIntegerField(default=24, verbose_name='K?ch thc ?nh n?i 2 (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chch?y 1'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chch?y 2'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chch?y 3'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_4',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chch?y 4'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_5',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chch?y 5'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='?ng d?n video thumbnail'),
        ),
        migrations.AlterField(
            model_name='part2topic',
            name='data_choices',
            field=models.TextField(blank=True, help_text='Nhập nhiều data rows answer. 4 voice sẽ chọn answer đúng từ danh sách này.', verbose_name='Data answer tổng'),
        ),
        migrations.AlterField(
            model_name='part2topic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên topics'),
        ),
        migrations.AlterField(
            model_name='part2topic',
            name='version',
            field=models.CharField(choices=[('gioi', 'Version A'), ('kem', 'Version B')], default='gioi', max_length=20, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='answer_a',
            field=models.CharField(blank=True, max_length=255, verbose_name='Answer A'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='answer_b',
            field=models.CharField(blank=True, max_length=255, verbose_name='Answer B'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='answer_c',
            field=models.CharField(blank=True, max_length=255, verbose_name='Answer C'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='answer_d',
            field=models.CharField(blank=True, max_length=255, verbose_name='Answer D'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Answer đúng'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='correct_data',
            field=models.TextField(blank=True, verbose_name='Answer đúng'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='data_choices',
            field=models.TextField(blank=True, help_text='Nhập nhiều ý data, mỗi ý một dòng. Khi làm bài chỉ chọn 4 ý tương ứng 4 người.', verbose_name='Data answer'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Lock'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='question_text',
            field=models.TextField(blank=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='core.part2topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='part2voice',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='Nội dung recording file'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID student'),
        ),
        migrations.CreateModel(
            name='Part3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('statement', models.TextField(blank=True)),
                ('correct_answer', models.CharField(blank=True, max_length=50)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.part3topic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
