# Generated by Django 5.2.14 on 2026-05-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_part3topic_alter_listeningpartquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginoverlayimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Login floating image', 'verbose_name_plural': 'Login floating image'},
        ),
        migrations.AlterModelOptions(
            name='loginthumbnail',
            options={'verbose_name': 'Login thumbnail', 'verbose_name_plural': 'Login thumbnail'},
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='voice_info',
            field=models.TextField(blank=True, verbose_name='Voice information'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='voice_info_locked',
            field=models.BooleanField(default=False, verbose_name='Lock voice information'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='image',
            field=models.ImageField(upload_to='login_overlay_images/', verbose_name='Floating image'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_images', to='core.loginthumbnail', verbose_name='Login thumbnail'),
        ),
        migrations.AlterField(
            model_name='loginoverlayimage',
            name='w',
            field=models.PositiveIntegerField(default=24, verbose_name='Size (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='login_thumbnails/', verbose_name='Thumbnail image upload'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Thumbnail image URL'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail name'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='login_overlay_images/', verbose_name='Floating image 1'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_left_w',
            field=models.PositiveIntegerField(default=26, verbose_name='Floating image 1 size (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_left_x',
            field=models.PositiveIntegerField(default=6, verbose_name='Floating image 1 X (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_left_y',
            field=models.PositiveIntegerField(default=58, verbose_name='Floating image 1 Y (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_right_image',
            field=models.ImageField(blank=True, null=True, upload_to='login_overlay_images/', verbose_name='Floating image 2'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_right_w',
            field=models.PositiveIntegerField(default=24, verbose_name='Floating image 2 size (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_right_x',
            field=models.PositiveIntegerField(default=58, verbose_name='Floating image 2 X (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='overlay_right_y',
            field=models.PositiveIntegerField(default=50, verbose_name='Floating image 2 Y (%)'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ticker text 1'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ticker text 2'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ticker text 3'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_4',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ticker text 4'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='ticker_text_5',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ticker text 5'),
        ),
        migrations.AlterField(
            model_name='loginthumbnail',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Thumbnail video URL'),
        ),
    ]
