# Generated by Django 6.0.5 on 2026-05-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homebackground'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebackground',
            options={'verbose_name': 'Ảnh nền trang chủ', 'verbose_name_plural': 'Ảnh nền trang chủ'},
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening_audio/', verbose_name='File audio tải lên'),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên'),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='image',
            field=models.FileField(upload_to='home_backgrounds/', verbose_name='Ảnh nền'),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='title',
            field=models.CharField(default='Ảnh nền trang chủ', max_length=150, verbose_name='Tên ảnh'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_url',
            field=models.URLField(blank=True, verbose_name='Link audio ngoài'),
        ),
    ]
