# Generated by Django 6.0.5 on 2026-05-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_listeningquestion_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_content_type',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Loại file audio'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên file audio'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Mã file audio'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_provider',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Kho audio'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Dung lượng audio'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening_audio/', verbose_name='File audio local'),
        ),
    ]
