# Generated by Django 6.0.5 on 2026-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_listeningquestion_voice_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='voice_info_locked',
            field=models.BooleanField(default=False, verbose_name='Khóa thông tin voice'),
        ),
    ]
