# Generated by Django 6.0.5 on 2026-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listeningquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='?nh n?n trang ch?', max_length=150, verbose_name='T?n ?nh')),
                ('image', models.FileField(upload_to='home_backgrounds/', verbose_name='?nh n?n')),
                ('is_active', models.BooleanField(default=True, verbose_name='?ang s? d?ng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ng?y t?i l?n')),
            ],
            options={
                'verbose_name': '?nh n?n trang ch?',
                'verbose_name_plural': '?nh n?n trang ch?',
            },
        ),
    ]
