# Generated by Django 6.0.5 on 2026-05-09 22:03

import core.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_homebackground_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedAudioStorage(), upload_to='listening_audio/', verbose_name='File audio bảo mật'),
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Báo động đỏ')], default='medium', max_length=20, verbose_name='Mức độ')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do cảnh báo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Cảnh báo bảo mật',
                'verbose_name_plural': 'Cảnh báo bảo mật',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, verbose_name='Session key')),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Device ID')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Lần hoạt động gần nhất')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Phiên đăng nhập',
                'verbose_name_plural': 'Phiên đăng nhập thiết bị',
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'session_key')},
            },
        ),
    ]
