# Generated by Django 6.0.5 on 2026-05-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_listeningquestion_audio_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='listening_transcript',
            field=models.TextField(blank=True, verbose_name='Đề bài nghe / transcript'),
        ),
    ]
