# Generated by Django 6.0.5 on 2026-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4')], default=1, verbose_name='Part')),
                ('question_number', models.IntegerField(verbose_name='Số câu')),
                ('question_text', models.TextField(verbose_name='Câu hỏi')),
                ('audio_url', models.URLField(blank=True, verbose_name='Link audio')),
                ('option_a', models.CharField(max_length=255, verbose_name='Đáp án A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Đáp án B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Đáp án C')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Đáp án đúng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Câu hỏi Listening',
                'verbose_name_plural': 'Danh sách câu hỏi Listening',
                'ordering': ['part', 'question_number'],
            },
        ),
    ]
