# Generated by Django 6.0.5 on 2026-05-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_listeningquestion_listening_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Google Drive File ID'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='audio_drive_link',
            field=models.URLField(blank=True, verbose_name='Link Google Drive MP3'),
        ),
    ]
