# Generated by Django 6.0.5 on 2026-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_listeningquestion_audio_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID học viên'),
        ),
    ]
