# Generated by Django 6.0.5 on 2026-05-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentprofile_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part2Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên chủ đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Chủ đề Part 2',
                'verbose_name_plural': 'Chủ đề Part 2',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Part2Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự người nói')),
                ('audio_url', models.URLField(blank=True, verbose_name='File audio / Link audio')),
                ('answer_a', models.CharField(blank=True, max_length=255, verbose_name='Đáp án A')),
                ('answer_b', models.CharField(blank=True, max_length=255, verbose_name='Đáp án B')),
                ('answer_c', models.CharField(blank=True, max_length=255, verbose_name='Đáp án C')),
                ('answer_d', models.CharField(blank=True, max_length=255, verbose_name='Đáp án D')),
                ('transcript', models.TextField(blank=True, verbose_name='Nội dung file ghi âm')),
                ('data_choices', models.TextField(blank=True, help_text='Nhập nhiều ý dữ liệu, mỗi ý một dòng. Khi làm bài chỉ chọn 4 ý tương ứng 4 người.', verbose_name='Dữ liệu đáp án')),
                ('correct_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Đáp án đúng')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='core.part2topic', verbose_name='Chủ đề')),
            ],
            options={
                'verbose_name': 'Voice Part 2',
                'verbose_name_plural': 'Voice Part 2',
                'ordering': ['topic_id', 'order', 'id'],
            },
        ),
    ]
