# Generated by Django 6.0.5 on 2026-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_part2topic_audio_url_part2voice_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part2topic',
            name='version',
            field=models.CharField(choices=[('gioi', 'Mày giỏi'), ('kem', 'Mày kém')], default='gioi', max_length=20, verbose_name='Phiên bản'),
        ),
    ]
