# Generated by Django 6.0.5 on 2026-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_part2voice_correct_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='voice_info',
            field=models.TextField(blank=True, verbose_name='Thông tin của voice'),
        ),
    ]
